#!/bin/bash
# title			:BASHRC System
# description	:Reload the Shell environment
# author		:Jessica Brown
# date			:2020-01-25
# version		:4
# usage			:After install, just open a terminal
# notes			:This script is self installing
# bash_version	:4.1.5(1)-release
# ==============================================================================

function reload() {
    echo 'Reloading environment'
    # while read -r env; do export "$env"; done
    . ~/.bashrc
}
