#!/bin/bash

function userlist() {
    declare -a users=($(awk -F: '$3 > 999 && $3 < 60001 {print $1}' /etc/passwd))

    for user in "${users[@]}"; do
        userid=$(awk -v pat="${user}" -F ":" '$1~pat{print $3}' /etc/passwd)
        groups=($(groups ${user} | cut -d':' -f 2))
        echo -e "${user} - ${userid} - (${groups[@]})"
    done
}
