#!/bin/bash
# title			:BASHRC System
# description	:Extract several types of compressed files
# author		:Jessica Brown
# date			:2020-01-25
# version		:4
# usage			:extract filename.ext
# notes			:This script is self installing
# bash_version	:4.1.5(1)-release
# ==============================================================================

function up() {
    local d=""
    limit=$1
    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
        echo "Help System for up"
    else
        for ((i=1 ; i <= limit ; i++)); do
            d=$d/..
        done
        d=$(echo $d | sed 's/^\///')
        if [ -z "$d" ]; then
            d=..
        fi
        cd $d
    fi
}

upto () { # example: [/www/public_html/animals/hippopotamus/habitat/swamps/images] $ upto h[TAB][TAB] return hippopotamus and habitat
    if [ -z "$1" ]; then
        return
    fi

    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
        echo "Help System for upto"
    else
        local upto=$1
        cd "${PWD/\/$upto\/*//$upto}"
    fi
}

_upto() {
    local cur=${COMP_WORDS[COMP_CWORD]}
    local d=${PWD//\//\ }
    COMPREPLY=( $( compgen -W "$d" -- "$cur" ) )
}
complete -F _upto upto

jd() { # example: [/www/public_html/animals/hippopotamus] $ jd images takes you to [/www/public_html/animals/hippopotamus/habitat/swamps/images]
    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
        echo "Help System for upto"
    else
        if [ -z "$1" ]; then
            echo "Usage: jd [directory]";
            return 1
        else
            cd **"/$1"
        fi
    fi
}