#!/bin/bash
# title			:BASHRC System
# description	:The help system for BASHRC System
# author		:Jessica Brown
# date			:2019-12-20
# version		:4
# usage			:After install, just open a terminal
# notes			:This script is self installing
# bash_version	:4.1.5(1)-release
# ==============================================================================
# TODO:
#   Need to make this dynamically generated as new modules are added to the module folder
#   Vision: Have a function called <modulename>_help() it will contain a 1 liner and a
#           full description. The one liner would be generated inside this file and the
#           full description would be if they call that command with --help or (-h)

function commands() {
    cat ${binLocation}${dirSeperator}help.dat
}    

function under_construction() {
    help_screen 26
    cursorpos up 31; cursorpos col 30; echo -e "${White}HELP SYSTEM UNAVAILABLE" # 3 Chars
    cursorpos down 3; cursorpos col 25; echo -e "${Grey}_"
    cursorpos down 1; cursorpos col 24; echo -e "${Grey}/\`\\"
    cursorpos down 1; cursorpos col 17; echo -e "${Maroon}_n   ${Grey}/\` , \`\\"
    cursorpos down 1; cursorpos col 16; echo -e "${Maroon}|  |${Grey}/\` /\` \`\\ \`\\=========,________"
    cursorpos down 1; cursorpos col 16; echo -e "${Maroon}| ${Grey}/\` /${RosyBrown};-----;${Grey}\ \`\\        \`\\      \`\\"
    cursorpos down 1; cursorpos col 16; echo -e "${Grey}/\` /\` ${RosyBrown}||_|_|| ${Grey}\`\\ \`\\        \`\\      \`\\"
    cursorpos down 1; cursorpos col 14; echo -e "${Grey}/\` /\`${Silver}=  ${RosyBrown}||_|_||  ${Silver}=${Grey}\`\\ \`\\________\`\\______\`\\"
    cursorpos down 1; cursorpos col 12; echo -e "${Grey}/\`_/\`     '-----'     ${Grey}\`\\_\`\\-------;------|\""
    cursorpos down 1; cursorpos col 13; echo -e "${White}\"| ${RosyBrown}.---.   ${RosyBrown}.---. ${Silver}= ${RosyBrown}.---. ${White}|  ${RosyBrown}.--.  ${White}|${Silver}=${RosyBrown}.--.${White} |"
    cursorpos down 1; cursorpos col 13; echo -e "${White}| ${RosyBrown}|T_T|   ${RosyBrown}|T_T|   ${RosyBrown}|T_T| ${White}|  ${RosyBrown}|LI|  ${White}| ${RosyBrown}|LI|${White} |"
    cursorpos down 1; cursorpos col 13; echo -e "${White}| ${RosyBrown}|L_I|${Silver}=  ${RosyBrown}|L_I|   ${RosyBrown}|L_I|${White} |${Silver}= ${RosyBrown}|LI|${White}  | ${RosyBrown}|LI|${White} |"
    cursorpos down 1; cursorpos col 13; echo -e "${White}| ${RosyBrown}'---'   ${RosyBrown}'---' ${Grey}_.--._'${White} |  ${RosyBrown}'--' ${Silver}=| ${RosyBrown}'--'${White} |"
    cursorpos down 1; cursorpos col 12; echo -e "${White}_|__${Silver}=${White}_____${Silver}=${White}___${Grey},-" _.._ "-;${White}_${Silver}=${White}______|_____${Silver}=${White}|_"
    cursorpos down 1; cursorpos col 11; echo -e "${Grey}/_______________,-" __ "-._________T________\\"
    cursorpos down 1; cursorpos col 12; echo -e "${White}|| ${Silver}= ${RosyBrown}.----.   ${White}|| !|LI|! ||  ${RosyBrown}.--.  ${White}| ${RosyBrown}.--. ${White}||"
    cursorpos down 1; cursorpos col 12; echo -e "${White}||   ${RosyBrown}|LILI| ${Silver}= ${White}||  |  |  ||${Silver}= ${RosyBrown}|LI|  ${White}| ${RosyBrown}|LI|${Silver}=${White}||"
    cursorpos down 1; cursorpos col 12; echo -e "${White}||${Silver}=  ${RosyBrown}|LILI|${Silver}= _${White}JL_ | '| _JL_ ${RosyBrown}|LI|  ${White}|${Silver}=${RosyBrown}|LI| ${White}||"
    cursorpos down 1; cursorpos col 12; echo -e "${White}||  _${RosyBrown}'----' ${White}_|\"\"|_|__|_|\"\"| ${RosyBrown}'--' ${Silver}=${White}| ${RosyBrown}'--' ${White}||${Green}.--."
    cursorpos down 1; cursorpos col 12; echo -e "${White}|;${Green}-' )TTTT(\` ') ${IndianRed}|======|${Green}  |(\`\`\`-TTTTTTTTTT(    )\""
    cursorpos down 1; cursorpos col 9; echo -e "${Greem}\" \"\"(\`    )|(      )${IndianRed}|======|${Green}  (      )|||||||(      )"
    cursorpos down 1; cursorpos col 9; echo -e "${Green}jgs  '-Y-\`\"\"\"'- Y-'\"${Silver}/      \\ ${Green}\"\"\"\`--Y-\`\"\"\"\"\"\"\"\"'-Y--'\""
    cursorpos down 1; cursorpos col 9; echo -e "${Grey}^^^^^^^^^^^^^^^^^^^^        ^^^^^^^^^^^^^^^^^^^^^^^^^"
    cursorpos down 2; cursorpos col 22; echo -e "${Red}Currently this detailed help is under construction."
    cursorpos down 5
}