#!/bin/bash
# title			:BASHRC System
# description	:This is a startup script to make your bash experience useful
# author		:Jessica Brown
# date			:2020-01-25
# version		:1.4.2
# usage			:After install, just open a terminal
# notes			:This script is self installing
# bash_version	:4.1.5(1)-release
# ==============================================================================

function empty() { # Empty or create an existing file
	file="$1"
	if [ -f "$file" ];then
		cat /dev/null >"$file"
	else
		touch "$file"
	fi
}