#!/bin/bash
# title			:BASHRC System
# description	:This is a startup script to make your bash experience useful
# author		:Jessica Brown
# date			:2020-01-25
# version		:4
# usage			:After install, just open a terminal
# notes			:This script is self installing
# bash_version	:4.1.5(1)-release
# ==============================================================================
function netinfo () {
    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
        help_screen 5 2
        cursorpos up 16; cursorpos col 28; echo -e "${White}NET INFO (version 1.0)"
        cursorpos down 3; cursorpos col 4; echo -e "${Aqua}net_info ${White}- ${Silver}Shows network information in a clean formatted grid"
        cursorpos down 2; cursorpos col 4; echo -e "${Maroon}NOTICE: ${White}Several utilities are required to make this script work. Each utility"
        cursorpos down 1; cursorpos col 4; echo -e "${White}should automatically be installed during the install."
        cursorpos down 3; cursorpos col 4; echo -e "${White}EXAMPLE"
        cursorpos down 3; cursorpos col 4; echo -e "${Silver}$ ${White}netinfo"
        cursorpos down 4
    else
        clear_screen
        draw_screen 11 0 130

        ifcfg=/usr/sbin/ifconfig
        hwinf=/usr/sbin/hwinfo
        lynx=/usr/bin/lynx
        ip4fw=/usr/sbin/iptables
        ip6fw=/usr/sbin/ip6tables
        lspci=/usr/bin/lspci
        route=/usr/sbin/route
        netstat=/usr/bin/netstat
        lsb=/usr/bin/lsb_release

        [ -x ${hwinf} ] && network_ctrl="$(${hwinf} --network_ctrl)"

        unqID=$(grep "Unique\sID:\s[^ ]*" <<< $network_ctrl | sed 's/^.*: //' | tail -n 1)
        model=$(grep "Model:\s[^ ]*" <<< $network_ctrl | sed 's/^.*: //' | tail -n -1)
        vendor=$(grep "Vendor:\s[^ ]*" <<< $network_ctrl | sed 's/^.*: //' | tail -n -1)
        mac=$(grep "Permanent HW Address:\s[^ ]*" <<< $network_ctrl | sed 's/^.*: //' | tail -n -1)
        wlan_chan=$(grep "WLAN channels:\s[^ ]*" <<< $network_ctrl | sed 's/^.*: //' | tail -n -1)
        wlan_freq=$(grep "WLAN frequencies:\s[^ ]*" <<< $network_ctrl | sed 's/^.*: //' | tail -n -1)
        wlan_enc=$(grep "WLAN encryption modes:\s[^ ]*" <<< $network_ctrl | sed 's/^.*: //' | tail -n -1)

        # [ -x ${hwinf} ] && isa_pnp="${hwinf} --isapnp"
        [ -x ${ifcfg} ] && nic=$(${ifcfg} | grep RUNNING |grep -v LOOPBACK| awk '{print $1}' | cut -d " " -f 1)
        [ -x ${ifcfg} ] && iip=$(${ifcfg} | grep -w inet |grep -v 127.0.0.1| awk '{print $2}' | cut -d ":" -f 2)
        [ -x ${ifcfg} ] && iip6=$(${ifcfg} | grep -w inet6 | grep -v ::1| awk '{ print $2 }' | cut -d "/" -f 1)
        [ -x ${ifcfg} ] && inet=$(${ifcfg} | grep -w inet |grep -v 127.0.0.1| awk '{print $4}' | cut -d ":" -f 2)
        [ -x ${ifcfg} ] && broadcast=$(${ifcfg} | grep -w inet |grep -v 127.0.0.1| awk '{print $6}' | cut -d ":" -f 2)
        [ -x ${lynx} ] && exip="$(dig +short myip.opendns.com @resolver1.opendns.com)"
        hostname=$(hostname)
        kernel=$(uname -mrs)

        cursorpos up 16; cursorpos col 47; echo -e "${White}Network Information Panel (version 1.0)"
        cursorpos down 2; cursorpos col 4; echo -e "${Yellow}External IP address: ${Lime}${exip}"
        cursorpos up 2; cursorpos col 50; echo -e "${Yellow}Internal IP address: ${Lime}${iip}"
        cursorpos up 2; cursorpos col 97; echo -e "${Yellow}Net mask address: ${Lime}${inet}"
        cursorpos col 4; echo -e "${Yellow}IPv6 address: ${Lime}${iip6}"
        cursorpos up 2; cursorpos col 50; echo -e "${Yellow}Active NIC: ${Lime}${nic}"
        cursorpos up 2; cursorpos col 97; echo -e "${Yellow}Broadcast address: ${Lime}${broadcast}"
        cursorpos down 2; cursorpos col 4; echo -e "${Maroon}Unique ID: ${Red}${unqID}"
        cursorpos up 2; cursorpos col 60; echo -e "${Aqua}Channels: ${Teal}${wlan_chan}" | cut -c 1-87
        cursorpos up 1; cursorpos col 69; echo -e "${Aqua}Channels: ${Teal}${wlan_chan}" | cut -c 87-174
        cursorpos up 2; cursorpos col 4; echo -e "${Maroon}Model: ${Red}${model}"
        cursorpos col 4; echo -e "${Maroon}Vendor: ${Red}${vendor}"
        cursorpos up 1; cursorpos col 60; echo -e "${Aqua}Frequencies: ${Teal}${wlan_freq}" | cut -c 1-86
        cursorpos up 1; cursorpos col 73; echo -e "${Aqua}Frequencies: ${Teal}${wlan_freq}" | cut -c 87-139
        cursorpos up 1; cursorpos col 73; echo -e "${Aqua}Frequencies: ${Teal}${wlan_freq}" | cut -c 140-191
        cursorpos up 1; cursorpos col 73; echo -e "${Aqua}Frequencies: ${Teal}${wlan_freq}" | cut -c 192-242
        cursorpos up 4; cursorpos col 4; echo -e "${White}Host Name: ${Silver}${hostname}"
        cursorpos down 1; cursorpos col 4; echo -e "${White}Kernel: ${Silver}${kernel}"
        cursorpos down 2; cursorpos col 4; echo -e "${Fuchsia}Encryption Modes: ${Purple1}${wlan_enc}"

        # Create the bottom bar of screen
        cursorpos pos 17 0
    fi
}
