#!/usr/bin/env bash
# title			:BASHRC System
# description	:This is a startup script to make your bash experience useful
# author		:Jessica Brown
# date			:2019-12-20
# version		:4
# usage			:After install, just open a terminal
# notes			:This script is self installing
# bash_version	:4.1.5(1)-release
# ==============================================================================

# colored GCC warnings and errors
export EDITOR=${assignedEditor}
export LESS="-iMFXR"
export PAGER="/usr/bin/most -s"
export HISTIGNORE="&:ls:[bf]g:exit"
