#!/usr/bin/env bash
# title			:BASHRC System
# description	:This is a startup script to make your bash experience useful
# author		:Jessica Brown
# date			:2019-12-20
# version		:4
# usage			:After install, just open a terminal
# notes			:This script is self installing
# bash_version	:4.1.5(1)-release
# ==============================================================================

# Check if an assigned editor has been defined in the .bashrc.
if [[ $assignedEditor == "" ]]; then
    assignedEditor="vim"
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias ll='ls -alFh --color=auto'
    alias la='ls -A --color=auto'
    alias l='ls -CF --color=auto'
    alias dir='dir --color=auto'
    alias grep='grep --color=auto'
fi

# some more ls aliases
alias lt='du -sh * | sort -h'
alias q='exit'
alias quit='exit'
alias cls='clear; ls'
alias c='clear'
alias h='history'
alias k='kill'
alias null='/dev/null'
alias home='cd ~'
alias root='cd /'
alias resetperms='sudo chmod -R a=r,u+w,a+X'
alias nano=$assignedEditor
alias vi=$assignedEditor
alias vim=$assignedEditor
alias edit=$assignedEditor
alias start="systemctl start"
alias restart="systemctl restart"
alias stop="systemctl stop"
alias status="systemctl status"
alias viewcode="highlight -O ansi --force "
